name: Build example

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build
        run: pio run -e esp32s3
        env:
          PLATFORMIO_BUILD_FLAGS: -Werror -Wno-error=attributes -Wno-error=address-of-packed-member
